---
version: "3.8"

services:
  db:
    image: 'postgres:14-bullseye'
    container_name: onduken-db
    restart: always
    environment:
      - POSTGRES_USER=devroot
      - POSTGRES_PASSWORD=devrootpassword
      - POSTGRES_DB=onduken-db
      - PGDATA=/var/lib/postgresql/data
      - LANG=en_US.utf8
    networks:
      - shared-network
    volumes:
      - './postgresql-data:/var/lib/postgresql/data'
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'

  server:
    image: 'onduken-server:dev1'
    container_name: onduken-server
    restart: always
    build:
      context: server
    environment:
      - SERVER_PORT=5000 # server port
      - JWT_SECRET=someSecretKey
      - CLIENT_URL=http://localhost:3000
      - DB_URI=postgres://devroot:devrootpassword@onduken-db:5432/onduken-db
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - shared-network

  client:
    image: 'onduken-client:dev1'
    container_name: onduken-client
    restart: always
    build:
      context: client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - shared-network

  nginx:
    image: nginx:alpine
    container_name: onduken-nginx
    restart: always
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - "80:80"
      - "81:81"
    depends_on:
      - client
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge
